"""create form fields

Revision ID: 10fd389cc785
Revises: 775b12d4c851
Create Date: 2026-09-07 21:05:34.681277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fd389cc785'
down_revision: Union[str, Sequence[str], None] = '775b12d4c851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('field_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_version_id', 'field_order', name='uq_form_field_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_fields')
    # ### end Alembic commands ###
