"""agrega estado a proyectos

Revision ID: 116a620f2aba
Revises: c9ad91721f83
Create Date: 2026-08-27 16:32:00.304535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116a620f2aba'
down_revision: Union[str, Sequence[str], None] = 'c9ad91721f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.execute(
        "UPDATE projects SET status = 'active' "
        "WHERE status is NULL"
    )
    op.alter_column(
        "projects",
        "status",
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
