"""create survey answers

Revision ID: 1ae4dff73f76
Revises: 4bc481da57a9
Create Date: 2026-09-14 20:58:25.557730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae4dff73f76'
down_revision: Union[str, Sequence[str], None] = '4bc481da57a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('form_field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('field_option_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_option_id'], ['field_options.id'], ),
    sa.ForeignKeyConstraint(['form_field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'form_field_id', name='uq_survey_answer_field')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_answers')
    # ### end Alembic commands ###
