"""create survey answer corrections

Revision ID: 5a8df31c808a
Revises: 1ae4dff73f76
Create Date: 2026-09-18 07:58:48.455032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8df31c808a'
down_revision: Union[str, Sequence[str], None] = '1ae4dff73f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_answer_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_answer_id', sa.Integer(), nullable=False),
    sa.Column('corrected_by_user_id', sa.Integer(), nullable=False),
    sa.Column('old_value_text', sa.String(), nullable=True),
    sa.Column('old_value_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('old_value_date', sa.Date(), nullable=True),
    sa.Column('old_value_boolean', sa.Boolean(), nullable=True),
    sa.Column('old_field_option_id', sa.Integer(), nullable=True),
    sa.Column('new_value_text', sa.String(), nullable=True),
    sa.Column('new_value_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('new_value_date', sa.Date(), nullable=True),
    sa.Column('new_value_boolean', sa.Boolean(), nullable=True),
    sa.Column('new_field_option_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_field_option_id'], ['field_options.id'], ),
    sa.ForeignKeyConstraint(['old_field_option_id'], ['field_options.id'], ),
    sa.ForeignKeyConstraint(['survey_answer_id'], ['survey_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_answer_corrections')
    # ### end Alembic commands ###
