"""create field options

Revision ID: ad5f1c225711
Revises: 10fd389cc785
Create Date: 2026-09-11 09:57:45.807810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5f1c225711'
down_revision: Union[str, Sequence[str], None] = '10fd389cc785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_field_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('option_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_field_id'], ['form_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_field_id', 'option_order', name='uq_field_option_order'),
    sa.UniqueConstraint('form_field_id', 'value', name='uq_field_option_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_options')
    # ### end Alembic commands ###
