"""agrega descripcion a proyectos

Revision ID: c9ad91721f83
Revises: eb45a7a4ff7d
Create Date: 2026-08-26 21:48:39.569532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ad91721f83'
down_revision: Union[str, Sequence[str], None] = 'eb45a7a4ff7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
