"""agrega fecha de actualizacion a proyectos

Revision ID: cba21c519e2e
Revises: 2eac8bcfc540
Create Date: 2026-08-28 10:23:54.413776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba21c519e2e'
down_revision: Union[str, Sequence[str], None] = '2eac8bcfc540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
