"""agrega fechas operativas a proyectos

Revision ID: efe7f6d50478
Revises: cba21c519e2e
Create Date: 2026-08-28 11:22:28.441266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe7f6d50478'
down_revision: Union[str, Sequence[str], None] = 'cba21c519e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'projects',
        sa.Column('start_date', sa.Date(), nullable=True)
    )

    op.execute(
        "UPDATE projects "
        "SET start_date = CURRENT_DATE "
        "WHERE start_date IS NULL"
    )

    op.alter_column(
        'projects',
        'start_date',
        nullable=False
    )

    op.add_column(
        'projects',
        sa.Column('end_date', sa.Date(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
